FROM python:3.10-slim

# Настройка переменных среды
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_HOME='/usr/local' \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry'

# Установка poetry
RUN apt-get update; \
    apt-get install -y curl make build-essential; \
    curl -sSL https://install.python-poetry.org | python -

WORKDIR /code

# Установка зависимостей
COPY poetry.lock pyproject.toml /code/
RUN poetry install --no-root --no-dev

# Копирование приложения
COPY . .

# Запуск приложения
CMD ["make", "migrate-up"]
